name: Test Cases
on: [push, pull_request]
jobs: 
  CI-Actions-Ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Starting tests"
      - name: Checking out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: sudo apt-get install g++
      - run: make -C ${{ github.workspace }} -j$(nproc) run
      - name: Install libunwind-dev
        run: sudo apt-get install libunwind-dev libdwarf-dev=20200114-1 libdwarf1=20200114-1
      - run: make -C ${{ github.workspace }} RECOVER_VAR_NAMES=1 -j$(nproc) run
      - run: echo "Tests completed"
  CI-Actions-MacOs:
    runs-on: 	macos-latest
    steps:
      - run: echo "Starting tests"
      - name: Checking out repository
        uses: actions/checkout@v2
      - run: make -C ${{ github.workspace }} -j$(nproc) run
      - run: echo "Tests completed"
