matrix:
  include:
    - os: osx
      env:
        - MATRIX_EVAL="echo"
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

language: generic
script:
  - make run
